AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: KYC API that interacts with the SmartContract
Globals:
  Api:
    Cors:
      AllowOrigin: '''*'''
Resources:
  PostFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: index.post
      Runtime: nodejs8.10
      Policies:
      - SecretsManagerReadWrite
      - Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Action:
          - ec2:DescribeNetworkInterfaces
          - ec2:CreateNetworkInterface
          - ec2:DeleteNetworkInterface
          - ec2:DescribeInstances
          - ec2:AttachNetworkInterface
          Resource: '*'
      Timeout: 30
      Environment:
        Variables:
          RPC_ENDPOINT: https://rpc.slock.it/goerli
          CONTRACT_ADDRESS: '0x18b6cdb14A2cEEdc26379BE78B8116a5523c3075'
          KYC_VALIDATOR_ADDRESS: '0x09D8018F04de089a535A5a148CDfc28A72e5d439'
          KYC_VALIDATOR_PK: 7656CED238DFCD23014BD10D9F14156167C85679B46FBD9FF353A0C0C1D44EA8
      Events:
        GetResource:
          Type: Api
          Properties:
            Path: /kyc/{username}/{action}
            Method: POST
      CodeUri: s3://osb-sbhack19-lambda/7477d3751bfa4206b4629fdf86111eb3
